name: test
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npx prettier --check .

      - name: Convert YAML -> JSON
        run: npm run build

      - name: Run Tests
        run: npm test
